package br.com.pauloarcenio.gui;

import br.com.pauloarcenio.base.Base;
import br.com.pauloarcenio.dao.UsuarioDAO;
import br.com.pauloarcenio.entidades.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;

public class TelaUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form TelaUsuarios
     * @param parent
     * @param modal
     */
    public TelaUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        boolean entrarUser = TelaInicio.senhaADM();
        if (entrarUser) {
            initComponents();
            atualizaUsuarios();
        } else {
            this.dispose();
        }

    }

    private void atualizaUsuarios() {
        // TABELA DE USUARIOS
        String[] cposUsuarios = {"ID", "Login", "Senha"};
        List<Usuario> usuarios = UsuarioDAO.selecionarTodos();
        String[][] dadosUsuarios;
        dadosUsuarios = new String[usuarios.size()][3];
        int posicao = 0;
        for (Usuario user : usuarios) {
            String[] umUsuario = new String[3];
            umUsuario[0] = String.valueOf(user.getId());
            umUsuario[1] = user.getLogin();
            umUsuario[2] = String.valueOf(user.getSenha());
            dadosUsuarios[posicao++] = umUsuario;
        }
        DefaultTableModel modeloUser = new DefaultTableModel(
                dadosUsuarios, cposUsuarios);
        jtbUsuarios.setModel(modeloUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsuarios = new javax.swing.JTable();
        jtLogin = new javax.swing.JTextField();
        jtSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbCadastrarUsuario = new javax.swing.JButton();
        jbAlterarUsuario = new javax.swing.JButton();
        jbDeletarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Usuários");
        setIconImage(new ImageIcon(this.getClass().getResource("/br/com/pauloarcenio/images/padraologo.png")).getImage());
        setMinimumSize(new java.awt.Dimension(600, 400));

        jtbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbUsuarios);

        jLabel1.setText("Login:");

        jLabel2.setText("Senha:");

        jbCadastrarUsuario.setText("Cadastrar");
        jbCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarUsuarioActionPerformed(evt);
            }
        });

        jbAlterarUsuario.setText("Alterar");
        jbAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarUsuarioActionPerformed(evt);
            }
        });

        jbDeletarUsuario.setText("Deletar");
        jbDeletarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbDeletarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrarUsuario)
                    .addComponent(jbAlterarUsuario)
                    .addComponent(jbDeletarUsuario))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarUsuarioActionPerformed
        String login = jtLogin.getText().trim().toLowerCase();
        String senha = jtSenha.getText().trim().toLowerCase();
        boolean retornoSenha = TelaInicio.senhaADM();
        if (retornoSenha) {
            Usuario user = new Usuario(login, senha);
            UsuarioDAO.inserir(user);
            atualizaUsuarios();
        } else {
            JOptionPane.showMessageDialog(null, "Senha Inválida!");
        }

        jtLogin.setText("");
        jtSenha.setText("");
    }//GEN-LAST:event_jbCadastrarUsuarioActionPerformed

    private void jbDeletarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarUsuarioActionPerformed
        int selecionado = jtbUsuarios.getSelectedRow();
        if (jtbUsuarios.isRowSelected(selecionado)) {
            String idString = (String) jtbUsuarios.getValueAt(selecionado, 0);
            byte id = Byte.parseByte(idString);
            boolean retornoSenha = TelaInicio.senhaADM();
            if (retornoSenha) {
                UsuarioDAO.remover(UsuarioDAO.selecionaPeloID(id));
                atualizaUsuarios();
            } else {
                JOptionPane.showMessageDialog(null, "Senha inválida!");
            }
        } else {
            Base.mensagem("Selecione um usuário para apagar.");
        }
        jtLogin.setText("");
        jtSenha.setText("");
    }//GEN-LAST:event_jbDeletarUsuarioActionPerformed

    private void jbAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarUsuarioActionPerformed
        int selecionado = jtbUsuarios.getSelectedRow();
        if (jtbUsuarios.isRowSelected(selecionado)) {
            String idString = (String) jtbUsuarios.getValueAt(selecionado, 0);
            byte id = Byte.parseByte(idString);
            Usuario user = (UsuarioDAO.selecionaPeloID(id));
            boolean retornoSenha = TelaInicio.senhaADM();
            if (retornoSenha) {
                String login = jtLogin.getText();
                String senha = jtSenha.getText();
                if (!login.isEmpty() && !senha.isEmpty()) {
                    user.setLogin(login);
                    user.setSenha(senha);
                    UsuarioDAO.alterar(user);
                    atualizaUsuarios();
                } else {
                    Base.mensagem("Insira os dados para alterar!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Senha inválida!");
            }

        } else {
            Base.mensagem("Selecione um usuário para alterar.");
        }
        jtLogin.setText("");
        jtSenha.setText("");    }//GEN-LAST:event_jbAlterarUsuarioActionPerformed

    private void jtbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbUsuariosMouseClicked
        int selecionado = jtbUsuarios.getSelectedRow();
        if (jtbUsuarios.isRowSelected(selecionado)) {
            String idString = (String) jtbUsuarios.getValueAt(selecionado, 0);
            byte id = Byte.parseByte(idString);
            Usuario user = UsuarioDAO.selecionaPeloID(id);

            jtLogin.setText(user.getLogin());
            jtSenha.setText(user.getSenha());

        }
    }//GEN-LAST:event_jtbUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           TelaUsuarios dialog = new TelaUsuarios(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterarUsuario;
    private javax.swing.JButton jbCadastrarUsuario;
    private javax.swing.JButton jbDeletarUsuario;
    private javax.swing.JTextField jtLogin;
    private javax.swing.JTextField jtSenha;
    private javax.swing.JTable jtbUsuarios;
    // End of variables declaration//GEN-END:variables
}
