package br.com.pauloarcenio.gui;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

public class TelaSenhaADM extends javax.swing.JDialog {

    public boolean confirmaSenha = false;

    /**
     * Creates new form TelaSenhaADM
     *
     * @param parent
     * @param modal
     */
    public TelaSenhaADM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbConfirmaSenhaADM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtSenhaADM = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Senha Administrativa");
        setIconImage(new ImageIcon(this.getClass().getResource("/br/com/pauloarcenio/images/padraologo.png")).getImage());
        setMinimumSize(new java.awt.Dimension(425, 250));
        getContentPane().setLayout(null);

        jbConfirmaSenhaADM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jbConfirmaSenhaADM.setText("OK");
        jbConfirmaSenhaADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmaSenhaADMActionPerformed(evt);
            }
        });
        getContentPane().add(jbConfirmaSenhaADM);
        jbConfirmaSenhaADM.setBounds(290, 150, 75, 22);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("SENHA ADM:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 100, 109, 21);
        getContentPane().add(jtSenhaADM);
        jtSenhaADM.setBounds(260, 120, 140, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pauloarcenio/images/imgTelaLogin2.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDoubleBuffered(true);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(410, 210));
        jLabel2.setMinimumSize(new java.awt.Dimension(410, 210));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(410, 210));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 410, 210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmaSenhaADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmaSenhaADMActionPerformed
        char[] senhaUser = jtSenhaADM.getPassword();
        String senhaString = String.valueOf(senhaUser).trim().toLowerCase();
        boolean eIgual = TelaInicio.confereSenhaMestre(senhaString);
        if (!eIgual) {
            JOptionPane.showMessageDialog(null, "Senha Inválida!");
            jtSenhaADM.setText("");
        } else {
            confirmaSenha = true;
            this.dispose();
        }
    }//GEN-LAST:event_jbConfirmaSenhaADMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSenhaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSenhaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSenhaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSenhaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaSenhaADM dialog = new TelaSenhaADM(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JButton jbConfirmaSenhaADM;
    public static javax.swing.JPasswordField jtSenhaADM;
    // End of variables declaration//GEN-END:variables

}
